- hosts: public_all
  name: Monit info
  gather_facts: no
  sudo: yes
  roles:
    # - role: which
    #   which_application: monit
    - role: version
      version_application: monit
      version_arg: "-V"
